### ISSUE TITLE
The pypi package doesn't work on my system

### ISSUE THREAD

**Issue by Akuli** [PurpleMyst/mystcl#2]
I installed mystcl with `python3 -m pip install --user mystcl` and now I'm trying to use it

```
akuli@Akuli-Desktop:~$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mystcl
>>> mystcl.create()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
mystcl.TclError: Can't find a usable init.tcl in the following directories: 
    /usr/local/lib/tcl8.6 ./lib/tcl8.6 ./lib/tcl8.6 ./library ./library ./tcl8.6.9/library ./tcl8.6.9/library



This probably means that Tcl wasn't installed properly.

>>> 
akuli@Akuli-Desktop:~$ locate init.tcl
/usr/lib/blt2.5/init.tcl
/usr/share/tcltk/tcl8.5/init.tcl
/usr/share/tcltk/tcl8.6/init.tcl
akuli@Akuli-Desktop:~$ sudo ln -s /usr/share/tcltk/tcl8.6 /usr/local/lib/tcl8.6
akuli@Akuli-Desktop:~$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mystcl
>>> mystcl.create()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
mystcl.TclError: Can't find a usable init.tcl in the following directories: 
    /usr/local/lib/tcl8.6 ./lib/tcl8.6 ./lib/tcl8.6 ./library ./library ./tcl8.6.9/library ./tcl8.6.9/library

/usr/local/lib/tcl8.6/init.tcl: version conflict for package "Tcl": have 8.6.9, need exactly 8.6.6
version conflict for package "Tcl": have 8.6.9, need exactly 8.6.6
    while executing
"package require -exact Tcl 8.6.6"
    (file "/usr/local/lib/tcl8.6/init.tcl" line 19)
    invoked from within
"source /usr/local/lib/tcl8.6/init.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list source $tclfile]"


This probably means that Tcl wasn't installed properly.

>>> 
```

Is it possible to create a `mystcl` that will work on any version of Tcl 8 instead of requiring 8.6.6 exactly?

Also, the `mystcl.so` from v0.2.0 in github's release page worked on this system. I guess that might be because the version it was compiled on happened to match my Tcl version exactly.

```
akuli@Akuli-Desktop:~$ cd Downloads/
akuli@Akuli-Desktop:~/Downloads$ file libmystcl.so 
libmystcl.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=9271c4a4934fee80326d09c8e8d54d05e7c64361, not stripped
akuli@Akuli-Desktop:~/Downloads$ mv libmystcl.so mystcl.so
akuli@Akuli-Desktop:~/Downloads$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mystcl
>>> mystcl.create()
<TkApp object at 0x7fb543f3a288>
>>> 
```

**Comment by PurpleMyst** [comment]
This is odd. I'd expect the `mystcl` manylinux wheel to not depend on any dynamic libraries. I'll investigate this further once I have the time.
